name: CI
on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actions-k3s
        uses: debianmaster/actions-k3s@v1.0.5
        id: k3s
        with:
          version: 'v1.21.2-k3s1'
      - run: |
          kubectl get nodes
          kubectl get pods -A
          sleep 20
          kubectl get pods -A